[build]
  command = "ng build --configuration production"  # Gera uma build otimizada para produção
  publish = "dist/front-end"  # Diretório de publicação do build do front-end

[[redirects]]
  from = "/*"  # Todas as solicitações serão redirecionadas para o front-end (SPA)
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://projeto-gestao-servicos.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
