version: '3.8'

services:
  # Banco de dados PostgreSQL (descomentado, se necessário)
  # banco-pg:
  #   image: postgres:14
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_DB: servicos
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #   volumes:
  #     - postgres-data-servico-prestado:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"  # Mapeia a porta 5433 do host para a porta 5432 do container

  backend:
    build:
      context: .
    container_name: backend
    environment:
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      APP_PROFILE: ${APP_PROFILE}
    ports:
      - "8080:8080"  # Porta exposta para o contêiner
    # depends_on:
    #   - banco-pg

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # O arquivo de configuração do Nginx
      - /etc/letsencrypt:/etc/letsencrypt  # Para acessar os certificados SSL
    ports:
      - "80:80"   # Porta HTTP
      - "443:443" # Porta HTTPS
    depends_on:
      - backend  # Garante que o backend esteja ativo antes do Nginx

#volumes:
  # postgres-data-servico-prestado:
